version: '2.2'

services:

  db:
    image: postgres:12.1
    volumes:
      - pgdata:/var/lib/postgresql/data
      - '.dockerdev/init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  web:
    build: .
    command: >
      bash -c "[ ! -e /railsapp/tmp/pids/server.pid ] || rm /railsapp/tmp/pids/server.pid
      && bundle check || bundle install
      && rm -rf /railsapp/public/packs
      && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - '.:/railsapp'
      - .dockerdev/.bashrc:/root/.bashrc:ro  
      - bundle:/usr/local/bundle
      - node_modules:/railsapp/node_modules
    ports:
      - '127.0.0.1:3000:3000'
    depends_on:
      - db
    environment:
      - REDIS_URL=redis://redis:6379/1
      - RAILS_ENV=development

  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
      - 'web'
    build: .
    command: bundle exec sidekiq
    volumes:
      - bundle:/usr/local/bundle
      - '.:/railsapp'
      - '/railsapp/tmp' # don't mount tmp directory
    environment:
      - REDIS_URL=redis://redis:6379/1

volumes:
  bundle:
  pgdata:
  redis:
  node_modules:
